version: '3.8'

services:
  # 主节点
  llm-master:
    build: .
    container_name: llm-master
    ports:
      - "8080:8080"
      - "8081-8090:8081-8090"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - SERVER_PORT=8080
      - LLAMA_CPP_PORT=8081
      - JWT_SECRET=your-secret-key-change-in-production
      - DATABASE_URL=sqlite3://./data/llm.db
      - ENVIRONMENT=production
    networks:
      - llm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 工作节点 1
  llm-worker-1:
    build: .
    container_name: llm-worker-1
    ports:
      - "8180:8080"
      - "8181-8190:8081-8090"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - SERVER_PORT=8080
      - LLAMA_CPP_PORT=8081
      - JWT_SECRET=your-secret-key-change-in-production
      - ENVIRONMENT=production
      - CLUSTER_MODE=worker
      - MASTER_HOST=llm-master
      - MASTER_PORT=8080
    networks:
      - llm-network
    depends_on:
      - llm-master
    restart: unless-stopped

  # 工作节点 2
  llm-worker-2:
    build: .
    container_name: llm-worker-2
    ports:
      - "8280:8080"
      - "8281-8290:8081-8090"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - SERVER_PORT=8080
      - LLAMA_CPP_PORT=8081
      - JWT_SECRET=your-secret-key-change-in-production
      - ENVIRONMENT=production
      - CLUSTER_MODE=worker
      - MASTER_HOST=llm-master
      - MASTER_PORT=8080
    networks:
      - llm-network
    depends_on:
      - llm-master
    restart: unless-stopped

  # 负载均衡器 (可选)
  nginx:
    image: nginx:alpine
    container_name: llm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - llm-network
    depends_on:
      - llm-master
      - llm-worker-1
      - llm-worker-2
    restart: unless-stopped

  # 监控服务 (可选)
  prometheus:
    image: prom/prometheus:latest
    container_name: llm-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - llm-network
    restart: unless-stopped

  # 可视化监控 (可选)
  grafana:
    image: grafana/grafana:latest
    container_name: llm-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - llm-network
    restart: unless-stopped

networks:
  llm-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
